Intern Task Alina Mulik: Homework
alina-mulik/AlinaMulikSaysHello pull request #15
Opened 2023-01-14 18:46 UTC by alina-mulik

adding tests for homework 18 🥲 🤞

2023-01-16 20:05 UTC, yauhenists requested changes

2023-01-16 20:05 UTC, yauhenists commented on Homework18.EntityFrame/EntityFrameworkTests.cs
> +            Assert.IsTrue(!listOfNamesAfterDeletion.Contains(testUser));
You need to sleep at nights))
Not a mistake - you can use Assert.IsFalse without negation expression inside

2023-01-16 20:05 UTC, yauhenists commented on Homework18.EntityFrame/EntityFrameworkHelpers.cs
> +        public static List<User> GetEntityFrameworkDbInstance(Func<EntityFrameworkDbEntities, IQueryable<User>> func)
Method name says you can get any entity (rows from any tables) of EntityFrameworkDbEntities (database). Small changes can improve the method - please make the method generic.
Please ping me in case of any questions

2023-01-16 20:05 UTC, yauhenists commented on Homework18/AdonetHelpers.cs
> +using System.Data;
Please check usings ordering

2023-01-16 22:37 UTC, alina-mulik commented on Homework18.EntityFrame/EntityFrameworkTests.cs
> +            Assert.IsTrue(!listOfNamesAfterDeletion.Contains(testUser));
Fixed 😄

2023-01-16 22:44 UTC, alina-mulik commented on Homework18.EntityFrame/EntityFrameworkHelpers.cs
> +        public static List<User> GetEntityFrameworkDbInstance(Func<EntityFrameworkDbEntities, IQueryable<User>> func)
Fixed 💃

2023-01-16 22:46 UTC, alina-mulik commented on Homework18/AdonetHelpers.cs
> +using System.Data;
🥲 Sorry. Missed this. Fixed.

2023-01-17 10:54 UTC, yauhenists approved these changes

2023-01-17 11:01 UTC, alina-mulik commented
I did it! 😃

2023-01-17 11:01 UTC, merged